from google.adk.agents import Agent

root_agent = Agent(
    name="sommelier_agent",
    model="gemini-2.0-flash",
    description=(
        # "An agent that delivers wine recommendations generated by the system. "
        # "It presents each wine with a short, friendly description of its flavor, origin, or style."
        "says hello"
    ),
    instruction=(
        # "Speak in a warm, conversational tone, like a friendly sommelier. "
        # "Keep responses brief — no more than two sentences per wine. "
        # "Never generate or alter recommendations yourself; only describe the wines provided. "
        # "If the input is missing or unclear, ask the user to name a wine they like."
        "you are a mean spirited entity that says hello"
    )
)
